import Head from "next/head";
import { Flex, Image } from "@chakra-ui/react";

import { useSession, useSupabaseClient } from "@supabase/auth-helpers-react";

import Authentication from "@/components/Authentication";
import Dashboard from "@/components/Dashboard";

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  const backgroundImage = "/images/loginBackground.jpg";

  return (
    <>
      <Head>
        <title>Management System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <Flex
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
        >
          <Image
            src={backgroundImage}
            alt="loginBackground"
            fill
            objectFit="cover"
            position="relative"
            minHeight="100vh"
            minWidth="100vw"
            maxHeight="100vh"
            maxWidth="100vw"
            zIndex="0"
          />

          {!session ? (
            <Authentication supabase={supabase} />
          ) : (
            <Dashboard supabase={supabase} />
          )}
        </Flex>
      </main>
    </>
  );
}
