import Head from "next/head";
import Lottie from "lottie-react";
import animation404 from "../../public/images/PageNotFoundAnimation.json";
import {
  Box,
  Flex,
  Button,
  Heading,
  Image,
  Input,
  FormControl,
  FormLabel,
  Select,
  Text,
} from "@chakra-ui/react";

export default function PageNotFound() {
  return (
    <>
      <Head>
        <title>Page Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className="flex items-center justify-center h-screen">
        <Image
          src="/images/loginBackground.jpg"
          alt="loginBackground"
          fill
          objectFit="cover"
          position="absolute"
          minWidth="100vw"
          minHeight="100vh"
        />
        <Flex
          flexDirection="column"
          alignItems="center"
          justifyContent="center"
          position="relative"
          backgroundColor="white"
          color="gray.700"
          height="max-content"
          width="max-content"
          padding="2rem 1.5rem 2rem 1.5rem"
          maxWidth="88vw"
          borderRadius="6px"
          marginTop="-100px"
        >
          <Heading fontWeight="bold" color="black" zIndex="10" fontSize="54px">
            404
          </Heading>
          <Box
            height="300px"
            width="300px"
            marginTop="-80px"
            marginBottom="-55px"
          >
            <Lottie animationData={animation404} loop={true} />
          </Box>
          <p className="z-10 text-lg font-bold">Page Not Found.</p>
          <Button
            backgroundColor="gray.600"
            width="125px"
            borderRadius="2px"
            padding="0.1rem"
            marginTop="1rem"
            fontSize="12px"
            color="white"
            _hover={{ backgroundColor: "gray.700" }}
          >
            Go Back
          </Button>
        </Flex>
      </main>
    </>
  );
}
